name: Validate Private TagPacks

on:
  push:
    branches:
      - main
      - master

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Validate tagpacks
        run: |
          uvx --python ${{ matrix.python-version }} tagpack-tool tagpack validate packs

      - name: Validate Actors
        run: |
          uvx --python ${{ matrix.python-version }} tagpack-tool actorpack validate actors